service: graphql-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'ap-southeast-1'}
  stage: ${opt:stage, 'dev'}
  environment: ${file(.env.yml):${self:provider.stage}}

custom:
  serverless-offline:
    port: 4000

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
